# Generated by Django 3.2 on 2022-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Finished')], default=0, verbose_name='Status'),
        ),
    ]
