# Generated by Django 3.2 on 2022-02-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_last_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='guess_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Guess time'),
        ),
    ]
