# Generated by Django 3.2 on 2022-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_guess_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
