# Generated by Django 3.2 on 2022-02-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_card_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='word',
            field=models.CharField(max_length=30, verbose_name='Word'),
        ),
    ]
