# Generated by Django 3.2 on 2022-02-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20220211_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time_for_last_turn',
        ),
    ]
